### ISSUE TITLE
RSS配信が停止している

### ISSUE THREAD

**Issue by hagiwaratakayuki** [partakein/partake#484]
RSS配信が不明なエラーで停止しています

http://partake.in/feed/all

**Comment by KengoTODA** [comment]
ご報告いただきありがとうございます。RSS生成時に異常なデータが渡されることによる問題のようです。
以上データを含むイベントを削除しました（削除予告済みイベントでした）ので、現在は正常に動いています。

### 以下、開発者向け

```
2013-09-07 22:04:00,144 - [INFO] - from application in play-akka.actor.actions-dispatcher-24217 
redirectError
org.jdom.IllegalDataException: The data "..."  is not legal for a JDOM character content: Illegal Surrogate Pair.
    at org.jdom.Text.setText(Text.java:188) ~[jdom-1.0.jar:1.0]
    at org.jdom.Text.<init>(Text.java:99) ~[jdom-1.0.jar:1.0]
    at org.jdom.Element.addContent(Element.java:799) ~[jdom-1.0.jar:1.0]
    at com.sun.syndication.io.impl.RSS090Generator.generateSimpleElement(RSS090Generator.java:236) ~[rome-1.0.0.jar:na]
```

**Comment by mayah** [comment]
うーむ、malform な文字列を受け入れるところとそうでないところがあるとは……
